return {
    "Fruits",
    "TV Shows",
    "Birthday Party Items",
    "Movies",
    "Countries",
    "Animals",
    "Vegetables",
    "Colors",
    "Pizza Toppings",
    "Vehicles",
    "Video Games",
    "Fast Food Chains",
    "Superheroes",
    "Musical Instruments",
    "Musicians",
    "Ice Cream Flavors",
    "Dog Breeds",
    "Famous Athletes",
    "Cartoon Shows",
    "Anime",
    "Candy Brands",
    "Breakfast Foods",
    "Things at the Beach",
    "Things in a Kitchen",
    "Things That Can Fly",
    "US States",
    "Cereals",
    "Playground Games",
    "Youtubers",
    "Streamers",
    "Roblox Stuff",
    "Superpowers",
    "Kids Movies",
    "Toys",
    "Things on a Farm",
    "Builder Items",
    "Things in a School",
    "Things in a Bedroom",
    "School Subjects",
    "Sneaker Brands",
    "Clothing Brands",
    "Soda Brands",
    "Drinks",
    "Desserts",
    "Halloween Costumes",
    "Holidays",
    "Things That Are Cold",
    "Things That Are Hot",
    "Things That Are Round",
    "Things That Are Loud",
    "Types of Music",
    "Bugs",
    "Things in Space",
    "Underwater Things",
    "Emotes",
    "Emotions",
    "Movie Villains",
    "Cartoon Characters",
    "Body Parts"
}
